### PR TITLE
Use rustix instead of libc

### PR DESCRIPTION
**Pull request by swsnr**
rustix provides safe alternatives to everything we do with libc and
lets us get rid of a bunch of weird code.

### CODE REVIEW

**Comment by daniestevez** [comment]
[rustix's `memfd_create` implementation](https://github.com/bytecodealliance/rustix/blob/e35481c9a7e09eb24d4d67a4def48aa661fd52b3/src/backend/libc/fs/syscalls.rs#L1694) uses some [magic](https://github.com/bytecodealliance/rustix/blob/e35481c9a7e09eb24d4d67a4def48aa661fd52b3/src/weak.rs#L271) to call the libc function if present or perform a syscall if not. So it seems that this will solve the problems I described in #22, which is great news.

**Comment by swsnr** [comment]
I thought rustix doesn't use libc at all unless the use-libc feature was set?

In any case, it doesn't work, so don't have your hopes too high.  For some reason sending the FD over an unconnected socket returns EINVAL 🤷, hence the test failure. Haven't had time to take a closer look yet.

**Comment by daniestevez** [comment]
> I thought rustix doesn't use libc at all unless the use-libc feature was set?

I was reading the `#[cfg]`'s in `lib.rs` wrong. By default it uses the linux_raw backed, as the documentation says.

**Comment by swsnr** [comment]
Blocked on https://github.com/bytecodealliance/rustix/issues/884

**Comment by daniestevez** [comment]
Thank you! I have tested this new release in my embedded platform with an old glibc and it works perfectly. I can now continue using an unmodified version of this crate.

**Comment by swsnr** [comment]
Your welcome. It's just coincidental though; I just wanted to get rid of all the unsafe code 🙂

**Pull request merged**
